
### 统计
POST {{server}}/admin/utils/countAncient
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

###
type=importdizigui
type=importlistmap
type=importlistmaphuajianji
type=importlistmapsongci
type=importlistmapsongci1

type=importlistmaptangshi
type=importlistmaptangshi1
type=importlistmaptangshi2
type=importlistmaptangshi3
type=importlistmaptangshi4
type=importlistmaptangshi5
type=importlistmaptangshi6
type=importlistmaptangshi7
type=importlistmaptangshi8

type=importmaplist
type=importmaplistmap
type=importone

### import
POST {{server}}/admin/utils/importAncient
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

type=importqianziwen

### 论语
### 论语
POST {{server}}/admin/utils/importOneAncient
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

type=importlistmap&path=ci/ci.song.2009y.json&ancientSet=集部&ancientCategory=词曲类&bookName=全宋词&author=合著

