
### 统计
POST {{server}}/admin/utils/countAncient
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

###

### import
POST {{server}}/admin/utils/importAncient
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

type=importmaplistmap

### 论语
type=importmaplist
type=importone
type=importqianziwen
type=importdizigui
type=importlistmap
type=importlistmapsongci
type=importlistmaptangshi

