<#include '../frame/functions.ftlh'>

<#assign static>
    <!-- banner-->
    <link rel="stylesheet" href="/static/cssmoban/css/swiper.min.css">
    <script src="/static/cssmoban/js/swiper.min.js"></script>
    <script src="/static/cssmoban/js/banner.js"></script>
    <@StStatic prefix="" src="/static/cssmoban/js/index.js" />
</#assign>

<@PageFrame title=title static=static>
    待定blog
</@PageFrame>